In [2]:
myList1 = [1,2,3,4]
myList1

[1, 2, 3, 4]

In [3]:
myList2 = [2,3,4,5]
myList2

[2, 3, 4, 5]

In [2]:
import numpy as np

In [8]:
x = np.array([myList1,myList2])
x

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [9]:
x.shape

(2, 4)

In [19]:
n = np.arange(0,20,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
n.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [22]:
nn = np.linspace(0,10,8)
nn

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [25]:
np.ones([3,4],int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.zeros([2,3],int)

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
nn.dtype

dtype('float64')

In [37]:
nn.T.shape

(8,)

In [30]:
nn.std()

3.2732683535398857

In [31]:
nn.sum()

40.0

In [32]:
nn.min()

0.0

In [34]:
nn.mean()

5.0

In [35]:
#Get the index of element
nn.argmax()

7

In [36]:
nn.max()

10.0

In [38]:
nn.shape

(8,)

In [41]:
n = np.arange(40)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [55]:
n = n.reshape(8,5)
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [61]:
n[0,:-2]
n[1,:2]

array([5, 6])

In [62]:
test = np.random.randint(0,10,(3,4))

In [63]:
test

array([[6, 3, 0, 9],
       [2, 3, 9, 2],
       [7, 6, 1, 8]])

In [64]:
test2 = test**2

In [65]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

(array([6, 3, 0, 9]), '+', array([36,  9,  0, 81]), '=', array([42, 12,  0, 90]))
(array([2, 3, 9, 2]), '+', array([ 4,  9, 81,  4]), '=', array([ 6, 12, 90,  6]))
(array([7, 6, 1, 8]), '+', array([49, 36,  1, 64]), '=', array([56, 42,  2, 72]))


In [3]:
test = np.arange(1,37)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [4]:
test = test.reshape(6,6)

In [9]:
test

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [10]:
test[::3]

array([[ 1,  2,  3,  4,  5,  6],
       [19, 20, 21, 22, 23, 24]])

In [21]:
test[0][::-7]

array([6])

In [22]:
test.reshape(36)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])